### ISSUE TITLE
All files renamed to "Untittled" after begin uploaded

### ISSUE THREAD

**Issue by gentwins** [KehindeAdeyemi-apex/Save-files-to-Google-Drive#1]
Hello,

I don't know if this is just me or something, but all the files have been renamed to "Untitled" after uploaded?

**Comment by KehindeAdeyemi-apex** [comment]
Hi gentwins,

Thanks for your observation, Indeed it was getting renamed as "Untitled". I have fixed this issue to ensure the original file name (including extension).

Kindly redownload the plugin and replace in your app.

Please let me have your feedback
