### ISSUE TITLE
i am facing issue "There are no file uploaded"

### ISSUE THREAD

**Issue by kamranijaz1111** [KehindeAdeyemi-apex/Save-files-to-Google-Drive#2]
When i give your given api credential then its working fine. when i give my api's details it didn't upload file on drive. I have already followed file as you have given in source "configuration google api" but all invain.

Please guide
Regards

![Screenshot from 2021-04-27 12-53-32](https://user-images.githubusercontent.com/46958675/116205974-bd02c200-a757-11eb-9665-6428d1ce1d45.png)

**Comment by KehindeAdeyemi-apex** [comment]
Hello,

Sorry for the late response.

Please share set a google meeting so i can assist you.

Regards,
Kehinde

**Comment by haythemmousa** [comment]
i have the same issue 


When i give your given api credential then its working fine. when i give my api's details it didn't upload file on drive. I have already followed file as you have given in source "configuration google api" but all invain.
